### ISSUE TITLE
SQL Search "View definition" SQL editor doesn't fill available space

### ISSUE THREAD

**Issue by kburtram** [red-gate/foundry#1]
1. Run `View definition` command on a database object

Expected: The SQL editor fills all available space

Actual: There's some blank space below the editor and above the status bar

![screen](https://user-images.githubusercontent.com/599935/39222153-f7a54902-47ef-11e8-8335-d6b30b7f9711.png)

**Comment by Neone-pl** [comment]
Not only bellow, but also on the right.

![bez tytulu](https://user-images.githubusercontent.com/7324537/39305587-ebd3d926-495d-11e8-83a0-140700d1d442.png)

**Comment by cjgarland** [comment]
This issue has been fixed in version 0.2.1 of the extension.
