### ISSUE TITLE
Content for download page of sqlsearch extension for ADS

### ISSUE THREAD

**Issue by alanrenmsft** [red-gate/foundry#19]
https://www.redgatefoundry.com/apps/sql-search/Instructions 
'SQL Operations Studio' should be replaced with 'Azure Data Studio'
![image](https://user-images.githubusercontent.com/13777222/53661165-934fbe00-3c14-11e9-9ac2-31710733d232.png)

**Comment by stanislavHamara** [comment]
@alanrenmsft Thanks for letting us know. We reviewed all the mentions of SQL Ops Studio and changed it to Azure Data Studio.
