### ISSUE TITLE
Out of date .net core links in SQL Search readme

### ISSUE THREAD

**Issue by stanislavHamara** [red-gate/foundry#20]
![image](https://user-images.githubusercontent.com/6816380/53944393-2c6c5200-40b7-11e9-8b04-b25a0078fe4b.png)

**Comment by steebn** [comment]
Still broken...

**Comment by stanislavHamara** [comment]
Hello @steebn, thank you for raising this issue and we apologize for a delayed reply. 

Microsoft recently unified download links for all the platforms into one.
We will update the readme in our next release.
In the meantime, please use https://dotnet.microsoft.com/download to download .NET Core Runtime

**Comment by stanislavHamara** [comment]
This has now been fixed and will be released in `0.3.2` https://github.com/Microsoft/azuredatastudio/pull/4621
