### ISSUE TITLE
Error after choosing server

### ISSUE THREAD

**Issue by mrlife** [red-gate/foundry#23]
Azure Data Studio Version 1.6.0
Redgate SQL Search Version 0.3.2

The following error is produced after choosing the server:

>command 'vscode.previewHtml' not found

Steps to reproduce:

1. Press cmd-shift-p (macOS)
2. Type "SQL Search" to find the "Search in Active Connection" option and press enter
3. Type search term and press enter
4. The current server is highlighted, so press enter
5. See the error popup in the bottom-right of the screen

**Comment by sstolp** [comment]
I have the same issue

**Comment by BuffDogg** [comment]
Same issue.  Only difference it seems from your steps to reproduce is that I'm on windows.

Steps to reproduce:

Press ctrl-shift-p (windows 10 - 1803)
Type "SQL Search" to find the "Search in Active Connection" option and press enter
Type search term and press enter
The current server is highlighted, so press enter
See the error popup in the bottom-right of the screen

**Comment by stanislavHamara** [comment]
Hello,

Thank you for letting us know. This issue seems to be caused by Microsoft changing some of their [vscode API](https://github.com/Microsoft/vscode/issues/62630). We are investigating the issue and will keep you updated.

Thank you,
Stan

**Comment by stanislavHamara** [comment]
Hello,

Thank you for your patience. We've updated our use of vscode API and released SQL Search 0.3.3 which should be live at some point this week. This resolves the above issue.

Thank you,
Stan

**Comment by SamSharaf** [comment]
Kindly @stanislavHamara reopen.

Search fails with: 

> command 'vscode.previewHtml' not found

My system is: macOS 10.13.6
Azure Data Studio 1.7.0
Extension: Redgate SQL Search 0.3.3

**Comment by stanislavHamara** [comment]
Hello @SamSharaf,

to resolve this issue can you try reloading Azure Data Studio or restarting it completely after you install the new version? 

Please let us know if you still experience this problem after that.

Thank you,
Stan
