### ISSUE TITLE
command 'vscode.previewHtml' not found

### ISSUE THREAD

**Issue by sapan-sha** [red-gate/foundry#24]
Ctrl + Shift + P
SQL Search : Search in Active Connection 
"someSearchText"
It throw an popup "command 'vscode.previewHtml' not found"

**Comment by stanislavHamara** [comment]
Duplicate of https://github.com/red-gate/foundry/issues/23

**Comment by SamSharaf** [comment]
@stanislavHamara  Kindly reopen the original issue:
https://github.com/red-gate/foundry/issues/23#issuecomment-491386190
