### ISSUE TITLE
[SQL Search Error]^

### ISSUE THREAD

**Issue by dejan-shuki** [red-gate/foundry#35]
The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found. - The following frameworks were found: 3.0.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App] You can resolve the problem by installing the specified framework and/or SDK. The .NET Core frameworks can be found at: - https://aka.ms/dotnet-downloadIt was not possible to find any compatible framework version.

**Comment by adrianbanks** [comment]
The latest version (v0.4.0) of SQL Search has addressed this issue. .Net Core v3.1 is now supported.
