### ISSUE TITLE
[SQL Search Error]^

### ISSUE THREAD

**Issue by dimitri-b** [red-gate/foundry#36]
It was not possible to find any compatible framework version.
The suggested link  (https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.0.0&arch=x64&rid=win10-x64) returns the 3.11 downlad page, not the required older 2.0.0 version.

**Comment by adrianbanks** [comment]
The latest version (v0.4.0) of SQL Search has addressed this issue. .Net Core v3.1 is now supported.
