### ISSUE TITLE
command 'sqlSearch.searchInActiveConnection' not found

### ISSUE THREAD

**Issue by ben-farrant** [red-gate/foundry#38]
Cannot run a search in the latest version of ADS, it doesn't show a query text box, just a toast with the title error message.

> ____________________________________________________________
> Azure Data Studio
> --------------------------------------------------------------
> Version: 1.15.0 (system setup)
> Commit: e57eb999fc5f1e000477da8fe0b8679ff0bfd57b
> Date: 2020-02-12T20:48:43.389Z
> VS Code: 1.42.0
> Electron: 6.1.6
> Chrome: 76.0.3809.146
> Node.js: 12.4.0
> V8: 7.6.303.31-electron.0
> OS: Windows_NT x64 10.0.18363

**Comment by martincroft** [comment]
I get the same and also with the reindex - command 'sqlSearch.reindexActiveConnection' not found

Version: 1.15.0 (user setup)
Commit: e57eb999fc5f1e000477da8fe0b8679ff0bfd57b
Date: 2020-02-12T20:48:43.389Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Also doesn't work on insiders build
 Version: 1.16.0-insider
Commit: 71375808b9cf1a046d488187dab41a67b998f222
Date: 2020-02-14T05:57:41.833Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by adrianbanks** [comment]
Thanks for letting us know. This appears to be a problem only in the latest version of Azure Data Studio (v1.15.0).

We'll be investigating further and will keep you updated. Downgrading to [version 1.14.1](https://github.com/microsoft/azuredatastudio/releases/tag/1.14.1) should resolve the issue in the meantime.

**Comment by adrianbanks** [comment]
We have fixed this issue and released SQL Search v0.4.0 to address the problem. The latest version can be downloaded from [here](https://www.redgatefoundry.com/apps/sql-search/Instructions) and will appear in the extension market place soon.
