### ISSUE TITLE
Search not works. Azure Data Studio v1.15.0

### ISSUE THREAD

**Issue by alxlib** [red-gate/foundry#39]
Redgate SQL Search v 0.4.0

Message : command 'sqlSearch.reindexActiveConnection' not found
                 command 'sqlSearch.searchInActiveConnection' not found

**Comment by adrianbanks** [comment]
Duplicate of #38.

We have fixed this issue and released SQL Search v0.4.0 to address the problem. The latest version can be downloaded from here and will appear in the extension market place soon.
